#!/usr/bin/env ruby

require File.expand_path('../git_wrapper', __FILE__)
commit = GitCommit.new
asset = commit.asset_for_branch

exit unless asset
exit if commit.references? asset

msg = <<COMMIT_MSG
#{commit.message.strip}

VersionOne: #{asset}
#{commit.extra_comments.strip}
COMMIT_MSG

File.open(ARGV[0], 'w') { |f| f.write msg }

