#!/usr/bin/env ruby

require File.expand_path('../git_wrapper', __FILE__)

commit = GitCommit.new
asset = commit.asset_for_branch

exit unless asset # we're not on a branch for a story, defect, etc.

message = commit.message
message_sans_comments = message[/^[^#][.]*/]

exit if message_sans_comments.include? asset

File.open(ARGV[0], 'w') do |f|
  f.puts ''
  f.puts ''
  f.puts "VersionOne: #{asset}"
  f.puts message.strip
end

